# Site settings
title: " Blog -  WWS"
email: washwashsleep@email.com
description: > # We want wash wash sleep!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
#blog logo
logo: "https://avatars0.githubusercontent.com/u/9893415?v=3&s=200"
#blog cover
cover: "/assets/images/washsleep.jpg"
name: 'WWS'
author: 'WWS Team'
author_image: "/assets/images/author.gif"
paginate: 5
# Build settings
highlighter: pygments
markdown: kramdown
# twitter_username: jekyllrb
# github_username:  jekyll

social:
  # - icon: twitter
  #   url:  https://twitter.com/washwashsleep
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="
#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/washwashsleep
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:
