title: "Warehouse -  TMD Team (localhost)"
email: mobius@hiiir.com
description: > # this means to ignore newlines until "baseurl:"
  Tech, Infra, Do the right thing, that is what we are doing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
#blog logo
logo: "/assets/images/mobius_logo.jpg"
#blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
name: 'Mobius'
author: 'Mobius Ads'
author_image: "/assets/images/author.jpg"
paginate: 5
# Build settings
highlighter: pygments
markdown: kramdown
# twitter_username: jekyllrb
# github_username:  jekyll

social:
  - icon: twitter
    url:  https://twitter.com/tmder
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/tmder
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:
